### ISSUE TITLE
Remove swagger api

### ISSUE THREAD

**Issue by mhemrg** [duyluonglc/adonis-mongodb-boilerplate#108]
I was hoping to see an Adonis-MongoDB boilerplate but you have integrated swagger, too.
Can you please provide a version just for MongoDB integrations?

**Comment by duyluonglc** [comment]
Hi @mhemrg,
you can simple remove swagger and make your owner boilerplate without swagger

**Comment by mhemrg** [comment]
Thank you for your quick response, @duyluonglc.
It's just a suggestion. You know what, I think it would be better to have batteries included but removable.
I'm going to close the issue, but feel free to continue the discussion.
