### ISSUE TITLE
Auth logout gives me auth.logout is not a function

### ISSUE THREAD

**Issue by sredbull** [duyluonglc/adonis-mongodb-boilerplate#55]
auth console.log

`
Auth {
  _ctx: 
   { request: 
      Request {
        request: [Object],
        params: {},
        response: [Object],
        Config: [Object],
        _qs: {},
        _all: [Object],
        _body: [Object],
        _raw: {},
        _files: {},
        multipart: [Object] },
     response: 
      Response {
        request: [Object],
        response: [Object],
        _lazyBody: [Object],
        implicitEnd: true,
        Config: [Object] },
     session: 
      Session {
        _request: [Object],
        _response: [Object],
        _driverInstance: [Object],
        _isNewSessionId: false,
        _options: [Object],
        _key: 'adonis-session',
        _store: [Object],
        _sessionId: '065b0762-9d98-47b0-b7a7-f5081b7b62e1' } },
  Config: 
   Config {
     _configPath: '/Users/svenroodbol/Sites/feapp/webservice/config',
     _config: 
      { app: [Object],
        auth: [Object],
        bodyParser: [Object],
        cors: [Object],
        database: [Object],
        mail: [Object] } },
  _authenticatorsPool: 
   { jwt: 
      JwtScheme {
        _config: [Object],
        _serializerInstance: [Object],
        _instanceUser: [Object],
        _ctx: [Object],
        Encryption: [Object],
        _generateRefreshToken: [Object],
        jwtPayload: [Object] } },
  authenticatorInstance: 
   JwtScheme {
     _config: 
      { serializer: 'lucid',
        model: 'App/Models/User',
        scheme: 'jwt',
        uid: 'email',
        password: 'password',
        options: [Object] },
     _serializerInstance: 
      LucidSerializer {
        Hash: Hash {},
        _config: [Object],
        _Model: [Object],
        _queryCallback: null },
     _instanceUser: 
      User {
        __setters__: [Array],
        '$attributes': [Object],
        '$persisted': true,
        '$originalAttributes': [Object],
        '$relations': {},
        '$sideLoaded': {},
        '$parent': null,
        '$frozen': false,
        '$visible': undefined,
        '$hidden': [Array] },
     _ctx: { request: [Object], response: [Object], session: [Object] },
     Encryption: Encryption { encryptor: [Object] },
     _generateRefreshToken: Resetable { _originalValue: false, _val: false },
     jwtPayload: { uid: 5, iat: 1509991430 } },
  current: 
   JwtScheme {
     _config: 
      { serializer: 'lucid',
        model: 'App/Models/User',
        scheme: 'jwt',
        uid: 'email',
        password: 'password',
        options: [Object] },
     _serializerInstance: 
      LucidSerializer {
        Hash: Hash {},
        _config: [Object],
        _Model: [Object],
        _queryCallback: null },
     _instanceUser: 
      User {
        __setters__: [Array],
        '$attributes': [Object],
        '$persisted': true,
        '$originalAttributes': [Object],
        '$relations': {},
        '$sideLoaded': {},
        '$parent': null,
        '$frozen': false,
        '$visible': undefined,
        '$hidden': [Array] },
     _ctx: { request: [Object], response: [Object], session: [Object] },
     Encryption: Encryption { encryptor: [Object] },
     _generateRefreshToken: Resetable { _originalValue: false, _val: false },
     jwtPayload: { uid: 5, iat: 1509991430 } } }
`

**Comment by duyluonglc** [comment]
the auth with jwt does not have logout method so when do logout should remove jwt token from client

**Comment by jericopulvera** [comment]
@duyluonglc how do you make it so that the others won't be able to reuse token when they logout.
